# Generated by Django 5.1.7 on 2025-03-31 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_profile_name_profile_gelar_belakang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='klaster_pt',
            field=models.CharField(blank=True, choices=[('mandiri', 'Klaster Mandiri'), ('utama', 'Klaster Utama'), ('madya', 'Klaster Madya'), ('pratama', 'Klaster Pratama'), ('binaan', 'Klaster Binaan')], max_length=20, null=True, verbose_name='Klaster PT'),
        ),
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='institution',
            name='nama_pimpinan_pt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Pimpinan PT'),
        ),
        migrations.AddField(
            model_name='institution',
            name='nama_pimpinan_unit_ppm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Pimpinan Unit Pengelola PPM'),
        ),
        migrations.AddField(
            model_name='institution',
            name='nama_unit_ppm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Unit Pengelola PPM'),
        ),
        migrations.AddField(
            model_name='institution',
            name='nidn_pimpinan_pt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NIDN Pimpinan PT'),
        ),
        migrations.AddField(
            model_name='institution',
            name='nidn_pimpinan_unit_ppm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NIDN Pimpinan Unit Pengelola PPM'),
        ),
        migrations.AddField(
            model_name='institution',
            name='pt_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PT ID'),
        ),
        migrations.AddField(
            model_name='institution',
            name='sebutan_pimpinan_pt',
            field=models.CharField(blank=True, choices=[('rektor', 'Rektor'), ('ketua', 'Ketua'), ('direktur', 'Direktur')], max_length=50, null=True, verbose_name='Sebutan Pimpinan PT'),
        ),
        migrations.AddField(
            model_name='institution',
            name='sebutan_pimpinan_unit_ppm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sebutan Pimpinan Unit Pengelola PPM'),
        ),
        migrations.AddField(
            model_name='institution',
            name='sinta_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sinta ID'),
        ),
        migrations.AddField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_program_studi', models.CharField(max_length=255, verbose_name='Nama Program Studi')),
                ('ps_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='PS ID')),
                ('sinta_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sinta ID')),
                ('jenjang', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jenjang')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status')),
                ('akreditasi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Akreditasi')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_programs', to='main.institution', verbose_name='Institution')),
            ],
        ),
    ]
