# Generated by Django 5.1.7 on 2025-04-01 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_institution_klaster_pt_institution_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='program_studi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.programstudi', verbose_name='Program Studi'),
        ),
    ]
