# Generated by Django 5.1.7 on 2025-04-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_announcement_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementfile',
            name='file',
            field=models.FileField(upload_to='announcements/filesssss/', verbose_name='File Attachment'),
        ),
    ]
