# Generated by Django 5.1.7 on 2025-04-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_announcementfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementfile',
            name='file',
            field=models.FileField(upload_to='announcements/files/', verbose_name='File Attachment'),
        ),
    ]
