# Generated by Django 5.1.7 on 2025-04-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_profile_sinta_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sinta_score3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sinta Score'),
        ),
    ]
