# Generated by Django 5.1.7 on 2025-04-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_profile_sinta_score3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sinta_score3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sinta Score 3'),
        ),
    ]
