# Generated by Django 5.1.7 on 2025-04-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_profile_sinta_score3'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='sinta_score',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sinta Score'),
        ),
        migrations.AddField(
            model_name='institution',
            name='sinta_score3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sinta Score 3'),
        ),
    ]
