# Generated by Django 5.1.7 on 2025-04-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_institution_sinta_score_institution_sinta_score3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('system_owner', 'System Owner'), ('system_admin', 'System Admin'), ('institution_admin', 'Institutional Admin'), ('researcher', 'Researcher'), ('reviewer', 'Reviewer'), ('student', 'Student'), ('technician', 'Technician')], default='researcher', max_length=30, verbose_name='Role'),
        ),
    ]
