# Generated by Django 5.1.7 on 2025-04-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='sinta_scorego',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sinta Score Google Scholar'),
        ),
        migrations.AddField(
            model_name='institution',
            name='sinta_scoresc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sinta Score Scopus'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sinta_scorego',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sinta Score Google Scholar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sinta_scoresc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sinta Score Scopus'),
        ),
        migrations.AddField(
            model_name='programstudi',
            name='sinta_score',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sinta Score'),
        ),
        migrations.AddField(
            model_name='programstudi',
            name='sinta_score3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sinta Score 3'),
        ),
        migrations.AddField(
            model_name='programstudi',
            name='sinta_scorego',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sinta Score Google Scholar'),
        ),
        migrations.AddField(
            model_name='programstudi',
            name='sinta_scoresc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sinta Score Scopus'),
        ),
    ]
