# Generated by Django 5.1.7 on 2025-04-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_institution_sinta_scorego_institution_sinta_scoresc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='sinta_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Sinta ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sinta_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Sinta ID'),
        ),
        migrations.AlterField(
            model_name='programstudi',
            name='sinta_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Sinta ID'),
        ),
    ]
