# Generated by Django 5.1.7 on 2025-04-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_institution_sinta_id_alter_profile_sinta_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='akreditasi',
            field=models.CharField(blank=True, choices=[('internasional', 'Internasional'), ('unggul', 'Unggul'), ('baik_sekali', 'Baik Sekali'), ('baik', 'Baik'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('tidak_terakreditasi', 'Tidak Terakreditasi')], max_length=30, null=True, verbose_name='Akreditasi'),
        ),
    ]
