# Generated by Django 5.1.7 on 2025-04-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_institution_akreditasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='sinta_scorego',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='sinta_scoresc',
        ),
        migrations.RemoveField(
            model_name='programstudi',
            name='sinta_scorego',
        ),
        migrations.RemoveField(
            model_name='programstudi',
            name='sinta_scoresc',
        ),
        migrations.AlterField(
            model_name='programstudi',
            name='akreditasi',
            field=models.CharField(blank=True, choices=[('internasional', 'Internasional'), ('unggul', 'Unggul'), ('baik_sekali', 'Baik Sekali'), ('baik', 'Baik'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('tidak_terakreditasi', 'Tidak Terakreditasi')], max_length=30, null=True, verbose_name='Akreditasi PS'),
        ),
    ]
