# Generated by Django 5.1.7 on 2025-04-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_akreditasi_programstudi_akreditasi_ps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programstudi',
            name='jenjang',
            field=models.CharField(blank=True, choices=[('S3', 'S3'), ('Sp-2', 'Sp-2'), ('Sp-1', 'Sp-1'), ('S2', 'S2'), ('S1', 'S1'), ('D4', 'D4'), ('D3', 'D3'), ('D2', 'D2'), ('D1', 'D1')], max_length=10, null=True, verbose_name='Jenjang'),
        ),
        migrations.AlterField(
            model_name='programstudi',
            name='status',
            field=models.CharField(blank=True, choices=[('Aktif', 'Aktif'), ('Alih Bentuk', 'Alih Bentuk'), ('Tutup', 'Tutup'), ('Alih Kelola', 'Alih Kelola'), ('Pembinaan', 'Pembinaan')], max_length=50, null=True, verbose_name='Status'),
        ),
    ]
