# Generated by Django 5.1.7 on 2025-04-18 23:59

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.announcement_image_upload_path, verbose_name='Image Attachment'),
        ),
        migrations.AlterField(
            model_name='announcementfile',
            name='file',
            field=models.FileField(upload_to=main.models.announcement_file_upload_path, verbose_name='File Attachment'),
        ),
    ]
