# Generated by Django 5.1.7 on 2025-04-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_announcement_image_alter_announcementfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sinta_name_match',
            field=models.BooleanField(default=False, help_text='True if local full name ≈ scraped SINTA-profile name', verbose_name='Name matches SINTA?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sinta_name_scraped',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SINTA Name (scraped)'),
        ),
    ]
