# Generated by Django 5.1.7 on 2025-04-19 08:52

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_announcement_image_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.announcement_image_upload_path, verbose_name='Image Attachment'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='logo_bp',
            field=models.ImageField(blank=True, null=True, upload_to='institution_logo_upload_path', verbose_name='Logo BP'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.profile_photo_upload_path, verbose_name='Profile Photo'),
        ),
    ]
