# Generated by Django 5.1.7 on 2025-04-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_announcement_image_alter_institution_logo_bp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='jabatan_akademik',
            field=models.CharField(blank=True, choices=[('guru_besar', 'Guru Besar'), ('lektor_kepala', 'Lektor Kepala'), ('lektor', 'Lektor'), ('asisten_ahli', 'Asisten Ahli'), ('tenaga_pengajar', 'Tenaga Pengajar')], max_length=50, null=True, verbose_name='Jabatan Akademik'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jenjang_pendidikan',
            field=models.CharField(blank=True, choices=[('S3', 'S3'), ('Sp-2', 'Sp-2'), ('Sp-1', 'Sp-1'), ('S2', 'S2'), ('S1', 'S1'), ('D4', 'D4'), ('D3', 'D3'), ('D2', 'D2'), ('D1', 'D1')], max_length=50, null=True, verbose_name='Jenjang Pendidikan'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='orcid_id',
            field=models.URLField(blank=True, null=True, verbose_name='Orcid ID'),
        ),
    ]
