"""
Django settings for exploserve_project project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------------------------------------------------------
# SECURITY & DEBUG
# -------------------------------------------------------------------
SECRET_KEY = 'django-insecure-5h)trgtdp=%(ec!wk99@e=(k5pwiim82q)3k4w#rkkv#yndupe'
DEBUG = False
ALLOWED_HOSTS = ['exploservo.stikomyos.ac.id']

# -------------------------------------------------------------------
# Application definition
# -------------------------------------------------------------------
INSTALLED_APPS = [
    # Default Django apps:
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps:
    "django_bootstrap5",
    'widget_tweaks',
    
    # Local apps:
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'exploserve_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Add your template directories here if needed.
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.footer_columns',
            ],
        },
    },
]

WSGI_APPLICATION = 'exploserve_project.wsgi.application'

# -------------------------------------------------------------------
# Database configuration (MySQL)
# -------------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'exploserve_db',  # Your MySQL database name
        'USER': 'exploserve_user',           # Your MySQL username
        'PASSWORD': 'admin@bai#x$5b',           # Replace with your MySQL password
        'HOST': 'localhost',  # Set to 'localhost' or your database server IP
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

# -------------------------------------------------------------------
# Password validation
# -------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# -------------------------------------------------------------------
# Internationalization
# -------------------------------------------------------------------
LANGUAGE_CODE = 'en-id'  # Default language

LANGUAGES = [
    ('en', 'English'),
    ('id', 'Bahasa Indonesia'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',  # Where translation files will be stored
]

TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# -------------------------------------------------------------------
# Static and Media Files
# -------------------------------------------------------------------
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# -------------------------------------------------------------------
# Default primary key field type
# -------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------------------------------------------------------------------
# Authentication and Login/Logout settings
# -------------------------------------------------------------------
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = [
    'main.backends.EmailBackend',  # Custom backend using email
    'django.contrib.auth.backends.ModelBackend',
]

# -------------------------------------------------------------------
# Email Configuration (Console Backend for Development)
# -------------------------------------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# in production, switch to SMTP:
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = 587
#EMAIL_USE_TLS = True
# your Gmail address here
#EMAIL_HOST_USER = 'romanus@stikomyos.ac.id'
# for accounts with 2‑factor auth you must create an “App Password”:
#EMAIL_HOST_PASSWORD = '5emperF1d3l15'
#DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
#EMAIL_PORT = 465
#EMAIL_USE_SSL = False